### ISSUE TITLE
db:path syntax in <target> tags

### ISSUE THREAD

**Issue by andrus** [nhl/link-etl#12]
We should allow full Cayenne path syntax in the <target> tag of the extractor descriptor, including "db:somepath" variety. This would allow to match IDs, FK, etc. taking ETL closer to the database, potentially improving performance, and resulting in a clearer extraction model.

**Comment by atomashpolskiy** [comment]
Attribute.target is not for matching, but for resolving and setting target entity properties. Did you mean Mapper attributes?

**Comment by andrus** [comment]
This is implemented in other tasks and available in 1.4
