### ISSUE TITLE
Parameterized queries for Extractors

### ISSUE THREAD

**Issue by atomashpolskiy** [nhl/link-etl#25]
Would be nice to have parameterized extractor queries. Some thoughts on implementation details:

We may add an overloaded version of com.nhl.link.etl.runtime.task.MatchingTaskBuilder#withExtractor method with additional parameter being 'map of parameters' in case of named parameters or 'list of parameters' in case of position-indexed parameters. Default values should probably be provided by Java code. On extractor configuration level all parameters should be considered as mandatory; when value for parameter is not provided, exception should be thrown (at what moment: building or running ETL task?)

All currently existing extractor implementations seem to support some kind of query language (XPath, SQL, LDAP queries), so adding parameters into queries should not be a problem. May need to create simple query parsers for XPath and LDAP queries though. Determining the exact moment when query is parsed is related to exception logic (see above).

**Comment by andrus** [comment]
@atomashpolskiy : We already have an internal concept of parameters. See the uses of ExtractorParameters (two parameters are always passed: 'startToken', 'endToken'). So all the backend should already support parameters in its own specific fashion (e.g. SQL is translated to Cayenne SQLTemplate, that supports parameters already - http://cayenne.apache.org/docs/3.1/cayenne-guide/queries.html#sqltemplate ).

If we have scenarios that are not hadled by 'startToken' / 'endToken', we can expose this API to setup extra parameters.

**Comment by atomashpolskiy** [comment]
My concrete use case is rather trivial - to set bounds to the range of entries being processed. I've managed to make use of startToken as the lower bound, by subclassing SyncToken and overriding getInitialToken method to always return itself.
However, in my opinion it's sort of a hack, because SyncToken's purpose (based on usage in EtlTask) is to cut the overall set of entries into edible pieces, that can be processed simultaneously by different workers; startToken and endToken therefore determine the size of a batch, and it's not relevant to the business logic of ETL procedure; it's totally internal performance-related optimization.
That said, SyncToken may be used as the means of passing the only one "business" parameter in case of emergency, but I suppose it would be much better to separate these concepts.

**Comment by andrus** [comment]
Start/end tokens were initially developed as "markers" for serial processing to tell subsequent executions of the job where the last one finished. And you are right - they can be used for arbitrarily splitting the range of records for parallel processing as well. So yeah, those are partitioning, rather then business logic parameters.

So yeah, I am totally in favor of exposing API for any extra user parameters.

**Comment by andrus** [comment]
I am going to give this one a shot. My first cut of parameterized EtlTask looks like this:

public interface EtlTask {

	/**
	 * Creates and returns a new task based on this task, but bound to a set of
	 * named parameters.
	 * <p>
	 * Default extractor implementations would normally work with named
	 * parameters, but some would need positional parameters (e.g. LDAP
	 * extractor implemented by third-party). So internally we'd preserve
	 * incoming parameter ordering, and if you have an extractor that relies on
	 * positional bindings, make sure you pass an ordered map to this method.
	 * 
	 * @since 1.3
	 */
	EtlTask params(Map<String, Object> parameters);

	/**
	 * Creates and returns a new task based on this task and a {@link SyncToken}
	 * that helps to implement incremental synchronization.
	 * 
	 * @since 1.3
	 */

	EtlTask syncToken(SyncToken token);

	/**
	 * Executes the task returning {@link Execution} object that can be used by
	 * the caller to analyze the results. Currently all task implementations are
	 * synchronous, so this method returns only on task completion.
	 * 
	 * @since 1.1
	 */
	// TODO: Implement asynchronous tasks where {@link Execution} can be
	// use to watch progress, and gives the ability to cancel the task mid-way.
	Execution run();
    }
