### ISSUE TITLE
Communications link failure during commit(). Transaction resolution unknown.

### ISSUE THREAD

**Issue by vitalz** [nhl/link-etl#3]
2014 12:13:56] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during commit(). Transaction resolution unknown.

        at com.nhl.link.framework.etl.runtime.jdbc.JdbcRowReader.close(JdbcRowReader.java:50)

**Comment by andrus** [comment]
I guess that's a MySQL connection timeout and is a function of MySQL DataSource settings and the duration of the job. So while not directly related to link-etl, perhaps this should give us a motivation to read source data in chunks.

**Comment by andrus** [comment]
Not a LinkETL issue. Should be fixed on the app end. If newest Cayenne 4.0.M3 DataSourceBuilder is in use, the problem should go away.
