### ISSUE TITLE
Any example on how to use it?

### ISSUE THREAD

**Issue by aadrian** [nhl/link-etl#47]
Hi,

Is there any example on how to use it? Or is there any GUI for it?

Thank you.

**Comment by andrus** [comment]
Not yet. We'll work on the docs once the concept is stabilized (there's plenty of experimentation still going on with basic things).

There are no specific plans for the GUI as of yet. link-etl is purely a framework at the moment. But there's definitely a place for GUI to map sources to targets.

**Comment by andrus** [comment]
Actually here is a simple example:

```Java
// bootstrap shared runtime that will run tasks
DataSource srcDS = // define how you'd connect to  ETL source 
ServerRuntime targetRuntime = // Cayenne setup for ETL target .. targets are mapped in Cayenne 
EtlRuntime etl = EtlRuntimeBuilder()
          .withConnector("myconnector", new DataSourceConnector(srcDS))
          .withTargetRuntime(targetRuntime)
          .build();

// create a reusable task for a given transformation
EtlTask task = etl.getTaskService()
         .createOrUpdate(MyTargetEntity.class)
         .sourceExtractor("my-etl.xml)
         .matchBy(MyTargetEntity.NAME).task();

// run task, e.g. in a scheduled job
Execution e = task.run();
```

**Comment by aadrian** [comment]
@andrus 
Thank you for the example.

So the target entities need to be referenced directly ```MyTargetEntity.class```. Would it be possible to work with the CayenneModeler generated XML only, i.e. references to those nodes?

This way, a tool would not need to depend on user generated source code (compiled or not), only on configuration files. I suppose for a GUI would be much easier this way too.

E.g. In Scriptella http://scriptella.javaforge.com/ the execution can be defined in an XML file:
http://scriptella.javaforge.com/tutorial.html
It has the advantage that non-java developers can easily change stuff and re-execute.

**Comment by andrus** [comment]
Potentially yes. 

The original use case the tool was designed for is the apps that need to import data from somewhere. So the source structure is dynamic ("my-etl.xml"), but the target is "complied" (it has a Cayenne model and all the Java classes). If source structure changes, you simply change the XML (no need to even restart the app); but target changes happen within your own release cycle, so you would take advantage from compile-time checks, and etc. None of this contradicts your scenario to "work with the CayenneModeler generated XML".. I'd say the LOE to add 'createOrUpdate("MyTargetEntity")' should be pretty low.

**Comment by andrus** [comment]
I documented the example in this issue under the root README.md. Closing the issue.
